version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - app
###< doctrine/doctrine-bundle ###
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PROJECT_PATH}:/var/www/html
      - ./.docker/conf/nginx/local.crt:/var/www/ssl/local.crt
      - ./.docker/conf/nginx/local.key:/var/www/ssl/local.key
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - app
  php:
    image: dylanops/php:8.1
    restart: always
    container_name: php
    volumes:
      - ${PROJECT_PATH}:/var/www/html
    networks:
      - app
    environment:
      PHP_IDE_CONFIG: 'serverName=web'
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
networks:
  app:
    driver: bridge